name: BuildPDF
on:
  push:
    branches: [ master ]
    paths:
    - 'tex/**'
    - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install latex
        run: |
          sudo apt-get update --yes
          sudo apt-get dist-upgrade --yes
          sudo apt-get install --yes texlive-full

      - name: Install opam
        run: |
          sudo add-apt-repository ppa:avsm/ppa
          sudo apt-get update
          sudo apt-get install --yes opam
          opam init

      - name: Install ott
        run: opam install --yes ott

      - name: Build the paper
        run: |
          export PATH=$(opam config var prefix)/bin:$PATH
          cd tex
          make
          
      - uses: actions/upload-artifact@v3
        with:
          name: paper
          path: tex/paper.pdf

  mkrelease:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Variables
        id: vars
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: paper
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: paper-${{ steps.vars.outputs.date }}-${{ steps.vars.outputs.sha8 }}
          release_name: Main paper (version ${{ steps.vars.outputs.date }})
          draft: false
          prerelease: true
      - name: Upload pdf
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./paper.pdf
          asset_name: paper.pdf
          asset_content_type: application/pdf
